### ISSUE TITLE
Set custom typeface

### ISSUE THREAD

**Issue by MrNouri** [anugotta/FlipTImerView#1]
hi, thanks for this library.
How can i set custom typeface for text?

**Comment by anugotta** [comment]
Hey, Thanks for the feedback. I will add support for Custom typeface soon!

**Comment by MrNouri** [comment]
Thanks dear. i see your minSDK is 21. can you upper than 16 ?

**Comment by anugotta** [comment]
MinSDK is now 16

**Comment by MrNouri** [comment]
thanks dear friend.
i will wait you for support typeface.
thanks ❤️

**Comment by MrNouri** [comment]
hey bro, when you added this feature my bro?

**Comment by anugotta** [comment]
Hey @MrNouri was busy this weekend. Will definitely look into this on priority. Though i can't tell an exact date. I will let you know once its done.

**Comment by anugotta** [comment]
Resolved in v1.5
